# Keep the primary PC checkout untouched. Android's platform implementation is
# initially supplied by the already-tested NFSMW ReXGlue fork, not its game hooks.
set(TSG_GAME_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/extern/TheSimpsonsGameRecomp/simpsons")
include("${TSG_GAME_ROOT}/generated/default/sources.cmake")
add_library(tsg_recompiled OBJECT ${GENERATED_SOURCES})
target_compile_features(tsg_recompiled PRIVATE cxx_std_23)
target_include_directories(tsg_recompiled PRIVATE "${TSG_GAME_ROOT}/generated/default" "${TSG_GAME_ROOT}" compat)
target_link_libraries(tsg_recompiled PRIVATE rex::runtime)
target_compile_options(tsg_recompiled PRIVATE -g0 -O2 -fno-strict-aliasing -ffp-contract=off -fno-char8_t)
target_precompile_headers(tsg_recompiled PRIVATE "${TSG_GAME_ROOT}/generated/default/simpsons_init.h")
add_library(tsg_game SHARED src/game/android_game.cpp src/game/android_ring_wait.cpp src/game/android_touch.cpp $<TARGET_OBJECTS:tsg_recompiled>)
target_sources(tsg_game PRIVATE extern/android-reference/sdk/src/ui/rex_app.cpp)
foreach(source crt_native eye_shading frame_pacing game_clock ink_outlines physics_step subtitles tick_count)
    target_sources(tsg_game PRIVATE "${TSG_GAME_ROOT}/src/${source}.cpp")
endforeach()
target_compile_features(tsg_game PRIVATE cxx_std_23)
target_compile_definitions(tsg_game PRIVATE REXGLUE_BUILD_CONFIG="$<CONFIG>")
target_compile_options(tsg_game PRIVATE -O2 -g1 -fno-strict-aliasing -ffp-contract=off -fno-char8_t)
target_include_directories(tsg_game PRIVATE "${TSG_GAME_ROOT}" "${TSG_GAME_ROOT}/src" "${TSG_GAME_ROOT}/generated/default" compat)
target_link_libraries(tsg_game PRIVATE rex::runtime imgui::imgui log)
add_dependencies(tsg_game rexgpu-xenos)
target_link_options(tsg_game PRIVATE "-Wl,-z,max-page-size=16384")
add_library(tsg_gpu_probe SHARED src/game/gpu_probe.cpp)
target_include_directories(tsg_gpu_probe PRIVATE extern/android-reference/sdk/include extern/android-reference/sdk/thirdparty/vulkan-headers/include)
target_link_libraries(tsg_gpu_probe PRIVATE rex_android_gpu_driver dl)
target_link_options(tsg_gpu_probe PRIVATE "-Wl,-z,max-page-size=16384")
foreach(runtime_target rexcore rexui rexruntime rexgpu-xenos)
    target_compile_options(${runtime_target} PRIVATE -O2 -g1)
endforeach()
